//! Minimal read-only WebDAV server for the local-mount fallback.
//!
//! M1 scope (docs/MOUNT.zh-CN.md §4): the gateway lets each OS's built-in
//! WebDAV client (macOS WebDAVFS, Windows WebClient, Linux GVfs/davfs2)
//! browse and read a connection with zero driver installs. Only
//! OPTIONS / PROPFIND / HEAD / GET are served; every write verb is rejected
//! with 405 so the mount surface can never exceed the plugin's own
//! read-only policy.
//!
//! Zero new crates: hand-rolled HTTP/1.1 over a loopback `tokio` listener
//! (Cargo.lock is integrator-owned). Requests are `Connection: close`, the
//! path carries an in-memory random token (`/{token}/{connId}/{rel}`), and
//! anything without the token gets a plain 404 that does not reveal the
//! gateway's existence (§2.5 security boundary).

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::time::Duration;

use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{TcpListener, TcpStream};
use tokio::sync::Notify;

/// Hand-rolled boxed future — the `futures` crate stays out of Cargo.lock.
pub type BoxFut<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// One filesystem entry as the gateway renders it into PROPFIND XML.
/// `modified_ms` is Unix epoch milliseconds (`None` renders as unknown).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StatEntry {
    pub name: String,
    pub size: u64,
    pub is_dir: bool,
    pub modified_ms: Option<i64>,
}

/// Read-only view over one mounted connection. Implemented over the rclone
/// engine ops in the wiring layer; tests use an in-memory source.
pub trait GatewaySource: Send + Sync + 'static {
    fn stat(&self, rel: &str) -> BoxFut<'_, Result<StatEntry, String>>;
    fn list_dir(&self, rel: &str) -> BoxFut<'_, Result<Vec<StatEntry>, String>>;
    /// Whole-file read; M1 mounts target browsing and mid-size documents
    /// (no Range support). Implementations may cap the byte total.
    fn read(&self, rel: &str) -> BoxFut<'_, Result<Vec<u8>, String>>;
}

pub struct GatewayConfig {
    /// Connection id baked into every served path (`/{token}/{connId}/...`).
    pub conn_id: String,
    /// ≥128-bit random token; generated by the caller (strategy layer) and
    /// never persisted or logged.
    pub token: String,
    pub source: Arc<dyn GatewaySource>,
}

/// Live gateway handle: the loopback port plus the shutdown switch.
pub struct GatewayHandle {
    pub port: u16,
    pub token: String,
    /// `notify_one` stops the accept loop. Permit semantics: a notify that
    /// lands before the loop's first poll still stops it.
    pub shutdown: Arc<Notify>,
}

/// Per-connection head cap: a request line + headers never needs more.
const MAX_HEAD_BYTES: usize = 16 * 1024;
/// PROPFIND bodies are tiny filters; anything bigger is refused (413) so a
/// loopback peer cannot stream unbounded bytes into the sidecar.
const MAX_BODY_BYTES: usize = 64 * 1024;
/// Whole request/response cycle budget per socket (slowloris guard).
const CONNECTION_TIMEOUT: Duration = Duration::from_secs(30);

pub async fn start(config: GatewayConfig) -> Result<GatewayHandle, String> {
    let listener = TcpListener::bind("127.0.0.1:0")
        .await
        .map_err(|error| format!("gateway bind 127.0.0.1:0 failed: {error}"))?;
    let port = listener
        .local_addr()
        .map_err(|error| format!("gateway local_addr failed: {error}"))?
        .port();
    let shutdown = Arc::new(Notify::new());
    let shutdown_loop = shutdown.clone();
    let conn_id = config.conn_id;
    let source = config.source;
    let handle_token = config.token.clone();
    tokio::spawn(async move {
        let token = config.token;
        loop {
            tokio::select! {
                _ = shutdown_loop.notified() => break,
                accepted = listener.accept() => match accepted {
                    Ok((mut stream, _addr)) => {
                        let token = token.clone();
                        let conn_id = conn_id.clone();
                        let source = source.clone();
                        tokio::spawn(async move {
                            let _ = tokio::time::timeout(
                                CONNECTION_TIMEOUT,
                                serve_once(&mut stream, &token, &conn_id, &source),
                            )
                            .await;
                            let _ = stream.shutdown().await;
                        });
                    }
                    Err(_) => break,
                },
            }
        }
    });
    Ok(GatewayHandle {
        port,
        token: handle_token,
        shutdown,
    })
}

/// Parsed request head.
struct Request {
    method: String,
    /// Percent-decoded, token/connId-stripped relative path (`""` = root).
    rel: String,
    depth: u8,
    content_length: usize,
}

async fn serve_once(
    stream: &mut TcpStream,
    token: &str,
    conn_id: &str,
    source: &Arc<dyn GatewaySource>,
) -> Result<(), String> {
    let head_with_leftover = read_head(stream).await?;
    let request = match parse_head(&head_with_leftover.head, token, conn_id) {
        Some(request) => request,
        None => {
            // Unknown token or malformed request line: a bare 404 that does
            // not reveal what this port serves.
            return write_response(stream, "404 Not Found", &[], b"").await;
        }
    };
    // Drain the request body before answering (WebDAV PROPFIND carries an
    // XML filter we ignore for M1). Bytes that arrived in the same read as
    // the head are reused first — the socket may hold nothing more.
    if request.content_length > 0 {
        if request.content_length > MAX_BODY_BYTES {
            return write_response(stream, "413 Payload Too Large", &allow_header(), b"").await;
        }
        let mut remaining = request.content_length;
        remaining -= remaining.min(head_with_leftover.leftover.len());
        let mut sink = vec![0u8; remaining];
        if remaining > 0 {
            stream
                .read_exact(&mut sink)
                .await
                .map_err(|error| format!("body read failed: {error}"))?;
        }
    }

    match request.method.as_str() {
        "OPTIONS" => {
            write_response(
                stream,
                "200 OK",
                &[
                    ("DAV", "1".to_string()),
                    ("Allow", ALLOW_READ_ONLY_VALUE.to_string()),
                    ("MS-Author-Via", "DAV".to_string()),
                ],
                b"",
            )
            .await
        }
        "PROPFIND" => {
            let entry = match source.stat(&request.rel).await {
                Ok(entry) => entry,
                Err(_) => return write_response(stream, "404 Not Found", &[], b"").await,
            };
            let mut responses = vec![render_entry(token, conn_id, &request.rel, &entry)];
            if entry.is_dir && request.depth >= 1 {
                let children = source.list_dir(&request.rel).await.unwrap_or_default();
                for child in children {
                    let child_rel = if request.rel.is_empty() {
                        child.name.clone()
                    } else {
                        format!("{}/{}", request.rel, child.name)
                    };
                    responses.push(render_entry(token, conn_id, &child_rel, &child));
                }
            }
            let body = format!(
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<D:multistatus xmlns:D=\"DAV:\">\n{}\
                 </D:multistatus>\n",
                responses.concat()
            );
            write_response(
                stream,
                "207 Multi-Status",
                &[("Content-Type", "application/xml; charset=utf-8".to_string())],
                body.as_bytes(),
            )
            .await
        }
        "GET" | "HEAD" => {
            let entry = match source.stat(&request.rel).await {
                Ok(entry) => entry,
                Err(_) => return write_response(stream, "404 Not Found", &[], b"").await,
            };
            if entry.is_dir {
                return write_response(
                    stream,
                    "405 Method Not Allowed",
                    &allow_header(),
                    b"",
                )
                .await;
            }
            let bytes = match source.read(&request.rel).await {
                Ok(bytes) => bytes,
                Err(_) => return write_response(stream, "404 Not Found", &[], b"").await,
            };
            let length = bytes.len().to_string();
            let headers = [
                ("Content-Type", content_type(&request.rel)),
                ("Accept-Ranges", "none".to_string()),
            ];
            if request.method == "HEAD" {
                write_response_with_length(stream, "200 OK", &headers, &length, b"").await
            } else {
                write_response_with_length(stream, "200 OK", &headers, &length, &bytes).await
            }
        }
        _ => {
            write_response(stream, "405 Method Not Allowed", &allow_header(), b"").await
        }
    }
}

const ALLOW_READ_ONLY_VALUE: &str = "OPTIONS, GET, HEAD, PROPFIND";

fn allow_header() -> [(&'static str, String); 1] {
    [("Allow", ALLOW_READ_ONLY_VALUE.to_string())]
}

async fn read_head(stream: &mut TcpStream) -> Result<HeadRead, String> {
    let mut buffer = Vec::with_capacity(1024);
    let mut chunk = [0u8; 2048];
    loop {
        let read = stream
            .read(&mut chunk)
            .await
            .map_err(|error| format!("head read failed: {error}"))?;
        if read == 0 {
            return Err("client closed before head was complete".to_string());
        }
        buffer.extend_from_slice(&chunk[..read]);
        if let Some(position) = buffer
            .windows(4)
            .position(|window| window == b"\r\n\r\n")
        {
            let leftover = buffer[position + 4..].to_vec();
            buffer.truncate(position + 4);
            return Ok(HeadRead {
                head: String::from_utf8_lossy(&buffer).into_owned(),
                leftover,
            });
        }
        if buffer.len() > MAX_HEAD_BYTES {
            return Err("request head too large".to_string());
        }
    }
}

struct HeadRead {
    head: String,
    /// Bytes read past the head terminator — part of the request body.
    leftover: Vec<u8>,
}

/// Splits `/{token}/{connId}/{rel...}` and decodes it; `None` on any token,
/// conn-id, or shape mismatch (all collapse to the same 404).
fn parse_head(head: &str, token: &str, conn_id: &str) -> Option<Request> {
    let request_line = head.split("\r\n").next()?;
    let mut parts = request_line.split_whitespace();
    let method = parts.next()?.to_ascii_uppercase();
    let raw_path = parts.next()?;
    let path = raw_path.split('?').next().unwrap_or(raw_path);
    let decoded = percent_decode(path);
    let mut segments = decoded.split('/').filter(|segment| !segment.is_empty());
    if segments.next()? != token || segments.next()? != conn_id {
        return None;
    }
    let mut rel = String::new();
    for segment in segments {
        if segment == ".." {
            // Traversal attempt: same answer as a missing token.
            return None;
        }
        if segment == "." {
            continue;
        }
        if !rel.is_empty() {
            rel.push('/');
        }
        rel.push_str(segment);
    }
    let mut depth = 1u8;
    let mut content_length = 0usize;
    for line in head.split("\r\n").skip(1) {
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let value = value.trim();
        if key.trim().eq_ignore_ascii_case("depth") {
            depth = if value == "0" { 0 } else { 1 };
        } else if key.trim().eq_ignore_ascii_case("content-length") {
            content_length = value.parse().unwrap_or(0);
        }
    }
    Some(Request {
        method,
        rel,
        depth,
        content_length,
    })
}

async fn write_response(
    stream: &mut TcpStream,
    status: &str,
    headers: &[(&str, String)],
    body: &[u8],
) -> Result<(), String> {
    let length = body.len().to_string();
    write_response_with_length(stream, status, headers, &length, body).await
}

async fn write_response_with_length(
    stream: &mut TcpStream,
    status: &str,
    headers: &[(&str, String)],
    content_length: &str,
    body: &[u8],
) -> Result<(), String> {
    let mut head = format!("HTTP/1.1 {status}\r\nConnection: close\r\n");
    for (key, value) in headers {
        head.push_str(&format!("{key}: {value}\r\n"));
    }
    head.push_str(&format!("Content-Length: {content_length}\r\n\r\n"));
    stream
        .write_all(head.as_bytes())
        .await
        .map_err(|error| format!("write failed: {error}"))?;
    if !body.is_empty() {
        stream
            .write_all(body)
            .await
            .map_err(|error| format!("write failed: {error}"))?;
    }
    stream
        .flush()
        .await
        .map_err(|error| format!("flush failed: {error}"))
}

/// One `<D:response>` block. `rel` is the decoded relative path (`""` root).
fn render_entry(token: &str, conn_id: &str, rel: &str, entry: &StatEntry) -> String {
    let display_name = if rel.is_empty() {
        conn_id.to_string()
    } else {
        xml_escape(&entry.name)
    };
    let href = if rel.is_empty() {
        format!("/{token}/{conn_id}/")
    } else {
        format!("/{token}/{conn_id}/{}", href_encode(rel))
    };
    let (modified, created) = match entry.modified_ms {
        Some(ms) => {
            let datetime = chrono::DateTime::<chrono::Utc>::from_timestamp_millis(ms)
                .unwrap_or_default();
            (
                format!("<D:getlastmodified>{}</D:getlastmodified>\n", datetime.format("%a, %d %b %Y %H:%M:%S GMT")),
                format!(
                    "<D:creationdate>{}</D:creationdate>\n",
                    datetime.to_rfc3339_opts(chrono::SecondsFormat::Secs, true)
                ),
            )
        }
        // Omitted properties are legal in RFC 4918 PROPFIND responses.
        None => (String::new(), String::new()),
    };
    let size = if entry.is_dir {
        String::new()
    } else {
        format!("<D:getcontentlength>{}</D:getcontentlength>\n", entry.size)
    };
    let resource_type = if entry.is_dir {
        "<D:resourcetype><D:collection/></D:resourcetype>"
    } else {
        "<D:resourcetype/>"
    };
    format!(
        "<D:response>\n<D:href>{href}</D:href>\n<D:propstat>\n<D:prop>\n\
         <D:displayname>{display_name}</D:displayname>\n{size}{modified}{created}{resource_type}\n\
         </D:prop>\n<D:status>HTTP/1.1 200 OK</D:status>\n</D:propstat>\n</D:response>\n"
    )
}

fn xml_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// Percent-encoding for hrefs: unreserved bytes stay literal, `/` separates
/// segments, everything else becomes `%XX` (mirrors rc.rs's dependency-free
/// query encoding).
fn href_encode(rel: &str) -> String {
    let mut encoded = String::with_capacity(rel.len());
    for byte in rel.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'.' | b'_' | b'~' | b'/' => {
                encoded.push(byte as char)
            }
            _ => encoded.push_str(&format!("%{byte:02X}")),
        }
    }
    encoded
}

fn percent_decode(path: &str) -> String {
    let bytes = path.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == b'%' {
            let hex = bytes.get(index + 1..index + 3);
            if let Some(hex) = hex {
                if let Ok(value) = u8::from_str_radix(&String::from_utf8_lossy(hex), 16) {
                    decoded.push(value);
                    index += 3;
                    continue;
                }
            }
        }
        decoded.push(bytes[index]);
        index += 1;
    }
    String::from_utf8_lossy(&decoded).into_owned()
}

fn content_type(rel: &str) -> String {
    let extension = rel.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    let mime = match extension.as_str() {
        "txt" | "log" => "text/plain; charset=utf-8",
        "md" => "text/markdown; charset=utf-8",
        "html" | "htm" => "text/html; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "csv" => "text/csv; charset=utf-8",
        "json" => "application/json",
        "xml" => "application/xml",
        "pdf" => "application/pdf",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "svg" => "image/svg+xml",
        "js" => "text/javascript; charset=utf-8",
        _ => "application/octet-stream",
    };
    mime.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    struct MemSource {
        entries: HashMap<String, (u64, bool, i64)>,
        files: HashMap<String, Vec<u8>>,
    }

    impl MemSource {
        fn seeded() -> Self {
            let mut entries = HashMap::new();
            entries.insert("".to_string(), (0, true, 1_700_000_000_000));
            entries.insert("hello.txt".to_string(), (11, false, 1_700_000_001_000));
            entries.insert("sub".to_string(), (0, true, 1_700_000_002_000));
            entries.insert("sub/deep.md".to_string(), (5, false, 1_700_000_003_000));
            let mut files = HashMap::new();
            files.insert("hello.txt".to_string(), b"hello world".to_vec());
            files.insert("sub/deep.md".to_string(), b"# deep".to_vec());
            Self { entries, files }
        }
    }

    impl GatewaySource for MemSource {
        fn stat(&self, rel: &str) -> BoxFut<'_, Result<StatEntry, String>> {
            let result = self
                .entries
                .get(rel)
                .map(|(size, is_dir, modified_ms)| StatEntry {
                    name: rel.rsplit('/').next().unwrap_or("").to_string(),
                    size: *size,
                    is_dir: *is_dir,
                    modified_ms: Some(*modified_ms),
                })
                .ok_or_else(|| format!("not found: {rel}"));
            Box::pin(async move { result })
        }

        fn list_dir(&self, rel: &str) -> BoxFut<'_, Result<Vec<StatEntry>, String>> {
            let prefix = if rel.is_empty() {
                String::new()
            } else {
                format!("{rel}/")
            };
            let mut children: Vec<StatEntry> = self
                .entries
                .iter()
                .filter_map(|(path, (size, is_dir, modified_ms))| {
                    let child = path.strip_prefix(&prefix)?;
                    if child.is_empty() || child.contains('/') {
                        return None;
                    }
                    Some(StatEntry {
                        name: child.to_string(),
                        size: *size,
                        is_dir: *is_dir,
                        modified_ms: Some(*modified_ms),
                    })
                })
                .collect();
            children.sort_by(|a, b| a.name.cmp(&b.name));
            Box::pin(async move { Ok(children) })
        }

        fn read(&self, rel: &str) -> BoxFut<'_, Result<Vec<u8>, String>> {
            let result = self
                .files
                .get(rel)
                .cloned()
                .ok_or_else(|| format!("not found: {rel}"));
            Box::pin(async move { result })
        }
    }

    async fn spawn_gateway() -> (GatewayHandle, Arc<MemSource>) {
        let source = Arc::new(MemSource::seeded());
        let handle = start(GatewayConfig {
            conn_id: "conn1".to_string(),
            token: "tok123".to_string(),
            source: source.clone(),
        })
        .await
        .expect("gateway starts");
        (handle, source)
    }

    async fn request(method: &str, port: u16, path: &str) -> reqwest::Response {
        try_request(method, port, path)
            .await
            .expect("request should succeed while gateway is up")
    }

    async fn try_request(
        method: &str,
        port: u16,
        path: &str,
    ) -> Result<reqwest::Response, reqwest::Error> {
        reqwest::Client::new()
            .request(
                reqwest::Method::from_bytes(method.as_bytes()).expect("valid method"),
                format!("http://127.0.0.1:{port}{path}"),
            )
            .send()
            .await
    }

    #[tokio::test]
    async fn propfind_depth1_lists_children() {
        let (handle, _source) = spawn_gateway().await;
        let response = request("PROPFIND", handle.port, "/tok123/conn1/").await;
        assert_eq!(response.status(), 207);
        let body = response.text().await.expect("body");
        assert!(body.contains("hello.txt"), "root listing missing file: {body}");
        assert!(body.contains("sub"), "root listing missing dir: {body}");
        assert!(body.contains("multistatus"), "not a multistatus body: {body}");
    }

    #[tokio::test]
    async fn propfind_depth0_lists_only_self() {
        let (handle, _source) = spawn_gateway().await;
        let response = reqwest::Client::new()
            .request(reqwest::Method::from_bytes(b"PROPFIND").unwrap(), format!("http://127.0.0.1:{}/tok123/conn1/", handle.port))
            .header("Depth", "0")
            .send()
            .await
            .expect("response");
        assert_eq!(response.status(), 207);
        let body = response.text().await.expect("body");
        assert!(body.contains("conn1"));
        assert!(!body.contains("hello.txt"), "depth 0 leaked children: {body}");
    }

    #[tokio::test]
    async fn get_returns_file_bytes() {
        let (handle, _source) = spawn_gateway().await;
        let response = request("GET", handle.port, "/tok123/conn1/hello.txt").await;
        assert_eq!(response.status(), 200);
        assert_eq!(response.bytes().await.expect("bytes").as_ref(), b"hello world");
    }

    #[tokio::test]
    async fn head_reports_length_without_body() {
        let (handle, _source) = spawn_gateway().await;
        let response = request("HEAD", handle.port, "/tok123/conn1/hello.txt").await;
        assert_eq!(response.status(), 200);
        assert_eq!(
            response
                .headers()
                .get(reqwest::header::CONTENT_LENGTH)
                .and_then(|value| value.to_str().ok()),
            Some("11")
        );
        assert_eq!(response.bytes().await.expect("bytes").len(), 0);
    }

    #[tokio::test]
    async fn put_is_rejected_405() {
        let (handle, _source) = spawn_gateway().await;
        let response = reqwest::Client::new()
            .put(format!("http://127.0.0.1:{}/tok123/conn1/new.txt", handle.port))
            .body(b"data".to_vec())
            .send()
            .await
            .expect("response");
        assert_eq!(response.status(), 405);
    }

    #[tokio::test]
    async fn wrong_token_is_404() {
        let (handle, _source) = spawn_gateway().await;
        let response = request("GET", handle.port, "/wrongtoken/conn1/hello.txt").await;
        assert_eq!(response.status(), 404);
    }

    #[tokio::test]
    async fn missing_file_is_404() {
        let (handle, _source) = spawn_gateway().await;
        let response = request("GET", handle.port, "/tok123/conn1/nope.txt").await;
        assert_eq!(response.status(), 404);
    }

    #[tokio::test]
    async fn options_advertises_read_only_dav() {
        let (handle, _source) = spawn_gateway().await;
        let response = reqwest::Client::new()
            .request(reqwest::Method::OPTIONS, format!("http://127.0.0.1:{}/tok123/conn1/", handle.port))
            .send()
            .await
            .expect("response");
        assert_eq!(response.status(), 200);
        let dav = response
            .headers()
            .get("DAV")
            .and_then(|value| value.to_str().ok())
            .unwrap_or("");
        assert!(dav.contains('1'), "DAV header missing: {dav}");
        let allow = response
            .headers()
            .get("Allow")
            .and_then(|value| value.to_str().ok())
            .unwrap_or("");
        assert!(allow.contains("PROPFIND") && !allow.contains("PUT"), "Allow wrong: {allow}");
    }

    #[tokio::test]
    async fn shutdown_stops_the_listener() {
        let (handle, _source) = spawn_gateway().await;
        let port = handle.port;
        handle.shutdown.notify_one();
        tokio::time::sleep(std::time::Duration::from_millis(150)).await;
        assert!(
            try_request("GET", port, "/tok123/conn1/hello.txt")
                .await
                .is_err(),
            "listener still accepting after shutdown"
        );
    }
}
